server:
  port: 8083

spring:
  application:
    name: USER-JOB-MAPPING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/hiringx
    username: root
    password: sanjaysonu1@
    driverClassName: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
