server:
  port: 8080 # <-- Make sure this is the port you're using in browser

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: JOB-SERVICE
          uri: lb://jobs-service
          predicates:
            - Path=/jobs/**

        - id: USER-JOB-MAPPING-SERVICE
          uri: lb://user-job-mapping-service
          predicates:
            - Path=/userjobmapping/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
