server:
  port: 8084

spring:
  application:
    name: USER-SERVICE
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hiringx
      username: root
      password: sanjaysonu1@
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

